import React, {createContext, useContext, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter, NavLink, Navigate, Route, Routes, useNavigate} from 'react-router-dom';
import {LayoutDashboard, Users, Building2, PhoneCall, Headphones, ChartNoAxesCombined, ClipboardList, Settings, LogOut, Bell, Search, ChevronDown, ArrowUpRight, MoreHorizontal, Play, Filter} from 'lucide-react';
import {AreaChart,Area,ResponsiveContainer,XAxis,Tooltip,BarChart,Bar,Cell} from 'recharts';
import './styles.css';

const Auth=createContext(); const useAuth=()=>useContext(Auth);
const nav=[['Dashboard','/',LayoutDashboard],['Employees','/employees',Users],['Companies','/companies',Building2],['Calls','/calls',PhoneCall],['Recordings','/recordings',Headphones],['Reports','/reports',ChartNoAxesCombined],['Audit Logs','/audit-logs',ClipboardList],['Settings','/settings',Settings]];
const calls=[{id:'CALL-1042',name:'Priya Sharma',company:'Nexus Systems',type:'Outgoing',date:'Today, 10:42 AM',duration:'08:42',classification:'Business',recording:'Uploaded'},{id:'CALL-1041',name:'Arjun Mehta',company:'Atlas Infotech',type:'Incoming',date:'Today, 10:18 AM',duration:'03:16',classification:'Business',recording:'Uploaded'},{id:'CALL-1040',name:'Kavya Nair',company:'Brightline Media',type:'Outgoing',date:'Today, 09:56 AM',duration:'11:03',classification:'Business',recording:'Processing'},{id:'CALL-1039',name:'Rohan Kapoor',company:'—',type:'Incoming',date:'Yesterday, 5:24 PM',duration:'01:12',classification:'Personal',recording:'Not applicable'}];
const trend=[{d:'Mon',v:72},{d:'Tue',v:98},{d:'Wed',v:84},{d:'Thu',v:122},{d:'Fri',v:109},{d:'Sat',v:56},{d:'Sun',v:41}]; const employee=[{name:'Priya',calls:165},{name:'Arjun',calls:132},{name:'Kavya',calls:119},{name:'Rohan',calls:97}];
function Badge({children,kind}){return <span className={'badge '+(kind||String(children).toLowerCase().replaceAll(' ','-'))}>{children}</span>}
function Header({title,sub}){const {user}=useAuth(); return <header><div><h1>{title}</h1><p>{sub}</p></div><div className="header-actions"><button className="icon"><Search size={19}/></button><button className="icon bell"><Bell size={19}/><i/></button><div className="avatar">{user.name.split(' ').map(x=>x[0]).join('')}</div><div className="user"><b>{user.name}</b><small>{user.role.replace('_',' ')}</small></div><ChevronDown size={16}/></div></header>}
function Sidebar(){const {logout}=useAuth(); return <aside><div className="brand"><span>m</span><div>MIST <b>Avinya</b><small>Sales Intelligence</small></div></div><nav>{nav.map(([t,p,I])=><NavLink key={t} to={p} end={p==='/' }><I size={19}/>{t}</NavLink>)}</nav><div className="side-bottom"><div className="help"><b>Need help?</b><small>Visit support center</small></div><button onClick={logout}><LogOut size={19}/>Logout</button></div></aside>}
function Layout({children,title,sub}){return <><Sidebar/><main><Header title={title} sub={sub}/>{children}</main></>}
function Metric({title,value,change,icon,accent}){const I=icon;return <article className="metric"><div className={'metric-icon '+accent}><I size={20}/></div><div><p>{title}</p><h2>{value}</h2><small className="positive"><ArrowUpRight size={13}/>{change} <em>vs last month</em></small></div></article>}
function Dashboard(){return <Layout title="Good morning, Ananya" sub="Here’s what’s happening across your sales team today."><section className="metrics"><Metric title="Total Employees" value="86" change="12.5%" icon={Users} accent="purple"/><Metric title="Calls Today" value="248" change="8.2%" icon={PhoneCall} accent="blue"/><Metric title="Business Calls" value="187" change="14.6%" icon={Building2} accent="orange"/><Metric title="Total Call Duration" value="32h 18m" change="9.4%" icon={Headphones} accent="green"/></section><section className="grid-two"><article className="panel chart"><div className="panel-title"><div><h3>Calls overview</h3><p>Daily call volume this week</p></div><button className="select">This week <ChevronDown size={14}/></button></div><div className="chart-total"><b>682</b><span className="positive"><ArrowUpRight size={14}/> 12.8%</span></div><ResponsiveContainer width="100%" height={205}><AreaChart data={trend}><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#6c5ce7" stopOpacity=".28"/><stop offset="1" stopColor="#6c5ce7" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="d" axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="v" stroke="#6c5ce7" strokeWidth="3" fill="url(#fill)"/></AreaChart></ResponsiveContainer></article><article className="panel split"><div className="panel-title"><div><h3>Recording status</h3><p>Business call uploads</p></div><MoreHorizontal size={20}/></div><div className="donut"><div><b>87%</b><small>Uploaded</small></div></div><div className="legend"><span><i className="dot uploaded"/>Uploaded <b>163</b></span><span><i className="dot pending"/>Pending <b>18</b></span><span><i className="dot failed"/>Failed <b>6</b></span></div></article></section><section className="grid-two lower"><article className="panel"><div className="panel-title"><div><h3>Top performers</h3><p>Calls completed this week</p></div><MoreHorizontal size={20}/></div><ResponsiveContainer width="100%" height={220}><BarChart data={employee}><XAxis dataKey="name" axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="calls" radius={[6,6,0,0]} fill="#6c5ce7"/></BarChart></ResponsiveContainer></article><article className="panel quick"><div className="panel-title"><div><h3>Quick insights</h3><p>Performance at a glance</p></div></div><div className="insight"><span className="mini purple"><PhoneCall size={18}/></span><div><b>75.4%</b><p>Business call ratio</p></div><em>+4.2%</em></div><div className="insight"><span className="mini orange"><Building2 size={18}/></span><div><b>58</b><p>Companies contacted</p></div><em>+11.5%</em></div><div className="insight"><span className="mini green"><Headphones size={18}/></span><div><b>6m 42s</b><p>Avg. call duration</p></div><em>+7.8%</em></div></article></section><CallsTable compact/></Layout>}
function CallsTable({compact=false}){return <section className="panel table-panel"><div className="panel-title"><div><h3>{compact?'Recent activity':'All calls'}</h3><p>{compact?'Latest call activity from your team':'Search, filter and review call history'}</p></div>{compact&&<NavLink className="link" to="/calls">View all</NavLink>}</div>{!compact&&<div className="filters"><div><Search size={16}/>Search calls, people or companies</div><button><Filter size={16}/>Filters</button><button>Today <ChevronDown size={15}/></button></div>}<div className="table-wrap"><table><thead><tr><th>Employee</th><th>Company</th><th>Direction</th><th>Date & time</th><th>Duration</th><th>Classification</th><th>Recording</th><th/></tr></thead><tbody>{calls.map(c=><tr key={c.id}><td><span className="person">{c.name.split(' ').map(x=>x[0]).join('')}</span><div><b>{c.name}</b><small>{c.id}</small></div></td><td>{c.company}</td><td><span className={'direction '+c.type.toLowerCase()}>{c.type==='Incoming'?'↓':'↑'} {c.type}</span></td><td>{c.date}</td><td>{c.duration}</td><td><Badge>{c.classification}</Badge></td><td><Badge kind={c.recording==='Uploaded'?'uploaded':c.recording==='Processing'?'processing':'neutral'}>{c.recording}</Badge></td><td><button className="more"><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table></div>{!compact&&<div className="pagination">Showing 1–4 of 248 calls <div><button>‹</button><button className="current">1</button><button>2</button><button>3</button><button>›</button></div></div>}</section>}
function Listing({type}){const config={Employees:['Employees','Manage your sales team and monitor their activity'],Companies:['Companies','Manage your client companies and contacts'],Recordings:['Recordings','Secure business-call recordings from private storage'],Reports:['Reports','Analyze call activity and team performance'],Settings:['Settings','Manage your organization preferences'],Audit:['Audit logs','Review sensitive actions across the portal']}[type]; let content;if(type==='Employees')content=<Employees/>;else if(type==='Companies')content=<SimpleTable cols={['Company','Contact person','Industry','Assigned salesperson','Total calls','Last contacted']} rows={['Nexus Systems|Sanjay Iyer|Technology|Priya Sharma|43|Today','Atlas Infotech|Meera Rao|IT Services|Arjun Mehta|31|Yesterday','Brightline Media|Aditi Bose|Marketing|Kavya Nair|28|Aug 22']}/>;else if(type==='Recordings')content=<SimpleTable cols={['Employee','Company','Call date','Duration','File name','S3 status']} rows={['Priya Sharma|Nexus Systems|Aug 25, 2026|08:42|call-1042.m4a|Uploaded','Arjun Mehta|Atlas Infotech|Aug 25, 2026|03:16|call-1041.m4a|Uploaded','Kavya Nair|Brightline Media|Aug 25, 2026|11:03|call-1040.m4a|Processing']}/>;else content=<article className="panel empty"><ChartNoAxesCombined size={34}/><h3>{type} are ready</h3><p>This protected area is prepared for live MongoDB data.</p></article>;return <Layout title={config[0]} sub={config[1]}>{content}</Layout>}
function Employees(){return <SimpleTable cols={['Employee','Employee ID','Department','Status','Total calls','Business calls','Last call']} rows={['Priya Sharma|EMP-018|Enterprise Sales|Active|165|142|Today, 10:42 AM','Arjun Mehta|EMP-024|Inside Sales|Active|132|110|Today, 10:18 AM','Kavya Nair|EMP-031|Enterprise Sales|Active|119|98|Today, 9:56 AM','Rohan Kapoor|EMP-042|Field Sales|On leave|97|66|Yesterday']}/>}
function SimpleTable({cols,rows}){return <section className="panel table-panel"><div className="filters"><div><Search size={16}/>Search records</div><button><Filter size={16}/>Filters</button><button className="primary">+ Add new</button></div><div className="table-wrap"><table><thead><tr>{cols.map(x=><th key={x}>{x}</th>)}<th/></tr></thead><tbody>{rows.map((r,i)=><tr key={r}>{r.split('|').map((x,j)=><td key={j}>{x==='Active'?<Badge kind="uploaded">Active</Badge>:x==='On leave'?<Badge kind="processing">On leave</Badge>:x}</td>)}<td><button className="more"><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table></div></section>}
function Login(){const {login}=useAuth();const nav=useNavigate();function go(e){e.preventDefault();login();nav('/')}return <div className="login"><div className="login-card"><div className="login-brand"><span>m</span><b>MIST Avinya</b></div><h1>Welcome back</h1><p>Sign in to your admin portal.</p><form onSubmit={go}><label>Work email<input type="email" defaultValue="admin@mistavinya.local" required/></label><label>Password<input type="password" defaultValue="Admin@12345" required/></label><div className="login-row"><label className="check"><input type="checkbox"/> Remember me</label><a>Forgot password?</a></div><button className="primary wide">Sign in</button></form><small className="secure">Secure access for authorized MIST Avinya personnel</small></div></div>}
function App(){const [user,setUser]=useState({name:'MIST Avinya Admin',role:'ADMIN'});return <Auth.Provider value={{user,login:()=>setUser({name:'MIST Avinya Admin',role:'ADMIN'}),logout:()=>setUser(null)}}><Routes>{!user?<Route path="*" element={<Login/>}/>:<><Route path="/" element={<Dashboard/>}/><Route path="/employees" element={<Listing type="Employees"/>}/><Route path="/companies" element={<Listing type="Companies"/>}/><Route path="/calls" element={<Layout title="Calls" sub="Search, filter and review call history"><CallsTable/></Layout>}/><Route path="/recordings" element={<Listing type="Recordings"/>}/><Route path="/reports" element={<Listing type="Reports"/>}/><Route path="/audit-logs" element={<Listing type="Audit"/>}/><Route path="/settings" element={<Listing type="Settings"/>}/><Route path="*" element={<Navigate to="/"/>}/></>}</Routes></Auth.Provider>};createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
